### PR TITLE
Add NonrelatedTabularInline

### PR DESCRIPTION
**Pull request by yohanesmario**
This PR adds NonrelatedTabularInline to cater TabularInline instead of just StackedInline. The implementation uses code duplication, because I don't feel the need to use another abstraction, but feel free to suggest otherwise 😃

### CODE REVIEW

**Comment by yohanesmario** [comment]
@bhomnick Please kindly review 🙇🏼‍♂️

**Comment by bhomnick** [comment]
@yohanesmario Thanks for the contribution.  If you look at the Django source the only real difference between StackedInline and TabularInline is the template: https://github.com/django/django/blob/master/django/contrib/admin/options.py#L2199.  In order to avoid code duplication what I'd probably do is move everything currently in the `NonrelatedStackedInline` class up into a `NonrelatedInline` parent class and then have subclasses that inherit from both `NonrelatedInline` and `StackedInline` as well as `NonrelatedInline` and `TabularInline`.

**Comment by yohanesmario** [comment]
> @yohanesmario Thanks for the contribution. If you look at the Django source the only real difference between StackedInline and TabularInline is the template: https://github.com/django/django/blob/master/django/contrib/admin/options.py#L2199. In order to avoid code duplication what I'd probably do is move everything currently in the `NonrelatedStackedInline` class up into a `NonrelatedInline` parent class and then have subclasses that inherit from both `NonrelatedInline` and `StackedInline` as well as `NonrelatedInline` and `TabularInline`.

@bhomnick Yes that would work. I'll adjust it and get back to you. Thanks!

**Comment by yohanesmario** [comment]
@bhomnick adjusted as per your review 🙇🏼‍♂️

**Comment by ZviBaratz** [comment]
@bhomnick @yohanesmario Thanks for the awesome work! I would also really like to use the `TabularInLine` version, so let me know if I can help with this in any way.

**Comment by yohanesmario** [comment]
@bhomnick I will close this for now so it doesn't clutter our PR and Issue tracking. You may reopen this later if you want to merge this or discuss further.

**Comment by minchinweb** [comment]
Would love to see this merged and uploaded to PyPI!

**Comment by bhomnick** [comment]
@MinchinWeb 0.2 has just been released to PyPI with this added.

**Comment by minchinweb** [comment]
@bhomnick Thanks!!

**Pull request closed without merging**
